### PR TITLE
Merge Request from feature/friendship-v2 branch to develop branch

### PR DESCRIPTION
**Pull request by temesghentekeste**
Greetings from Temesghen!

Following the git-flow workflow, I merged the friendship-model feature branch to the develop branch and created a new feature branch by the name friendship-v2. Using that branch, I updated the friendship model to deal with the mutual friendship feature using two records in the friendships table. The tests are updated to test the new features.

Kindly request a pull request before I merge my feature branch to the develop branch.

Kind Regards,
Temesghen T.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Temesghen Bahta** 
Good job with your first submission  :muscle:  :muscle:
Your project meets most of the requirements :clap: :clap: :clap:  
There are just a few details to correct before you can go ahead:

- [ ] In friendship.rb model, remove commented code
- [ ] Timeline should only show the posts from the current user or their friends
- [ ] Each post should display the total number of likes
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by temesghentekeste** [comment]
Thanks @andresporras3423 for your review, I will do the same.

**Comment by temesghentekeste** [comment]
Hi,

I've addressed the aforementioned issues. Kindly request a pull request before I merge my feature branch to the develop branch.

Kind Regards,
Temesghen

**Review by javitocor — APPROVED** [review]
# STATUS APPROVED 🌟 🥇 

Congratulations you have met all the requirements! 👏 🥳 
Remember to fill up the completion form 📑  and you can move into the next project ⏩ 
Good luck! 😺

**Comment by temesghentekeste** [comment]
Thanks @javitocor for approving the project.

**Pull request closed without merging**
